### ISSUE TITLE
gabbi-run should support multiple input files

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#104]
It doesn't make much sense that `gabbi-run` currently only supports a single suite (via STDIN).

Ideally, it should be possible to pass multiple YAML files as positional arguments:

```
$ gabbi-run ... -- foo.yaml bar.yaml *.yaml
```

However, that's tricky because `target` and `prefix` are optional positional arguments. Thus we have no reasonable way to determine whether a positional argument is an input file (or do we?) - so we might have to resort to a named option (e.g. `-f`).

(According to @cdent, maintaining backwards compatibility is imperative.)

**Comment by cdent** [comment]
The recent tidying up in `runner.py` ought to make doing this a bit easier, but it is still the case that the files would need to be named an argument that either takes multiple files `-f foo.yaml,bar.yaml` or a multiple argument: `-f foo.yaml -f bar.yaml`.

I'm still not entirely convinced how doing so it better than running gabbi-run multiple times.

**Comment by FND** [comment]
Since the OP didn't clearly state the primary use case (which led to an unhelpful implementation in #179), let me restate it explicitly: It would be nice to support globbing in order to target all YAML files within a test directory.

> I'm still not entirely convinced how doing so it better than running gabbi-run multiple times.

AIUI we have two options:

1. Limit `gabbi-run` to a single file at a time, thus requiring a wrapper script to handle multiple files:

    ```bash
    set -e

    for filepath in *.yaml; do
        gabbi-run … < $filepath
    done
    ```

2. Support multiple files directly within `gabbi-run`:

    ```
    $ gabbi-run … *.yaml …
    ```

    (though of course it's still the shell taking care of globbing here)

While the former is not exactly arduous, it's kind of annoying - and not actually as straightforward as it might seem (think `failfast`, error reporting, etc.). Plus it's fairly common for CLI tools to support multiple files, so the latter is not an unreasonable expectation.

That leaves the question of how to design the CLI arguments, given the aforementioned constraints WRT positional arguments and backwards compatibility. I actually think the OP's implicit suggestion is quite a good one:

    $ gabbi-run … -- *.yaml

That is, use `--` as [end-of-options delimiter](http://unix.stackexchange.com/a/147745), which is to be followed only by file paths:

    $ gabbi-run --response-handler … localhost:8000 -- *.yaml

**Comment by cdent** [comment]
#180 closed this
