### ISSUE TITLE
assertion failure messages when using pytest are ugly and confusing

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#127]
They have many of the same issues that gabbi-run assertion reporting had before it's reporter was tweaked.

In the PyTestResult object something cleaner than just reraising the exception is required.

**Comment by cdent** [comment]
Actually this may not be as bad as I initially though. further investigation required

**Comment by keyhan** [comment]
Yes, as you put it the printouts are a bit too much and do not give any relevant information on what has failed and why.

**Comment by cdent** [comment]
Turns out that the output from a unittest runner or a pytest runner is fairly similar. It is quite verbose but the error or failed assertion ought to be in there, and at the end. Can you paste in an example of what you're seeing so we can compare notes?

One thing is that gabbi-run goes to great lengths to make the output far less verbose than the output from the non-human runners.

Here's a comparison of errors and failures in both pytest and subuni: http://paste.openstack.org/show/494314/

The same failure in gabbi-run:

```
shine:/tmp/foo $ gabbi-run < gabbits/test.yaml 
... ✗ first test

FAIL: first test
	'301' not found in ['200'], response:
	<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
	<html><head>
	<title>301 Moved Permanently</title>
	</head><body>
	<h1>Moved Permanently</h1>
	<p>The document has moved <a href="https://burningchrome.com/">here</a>.</p>
	<hr>
	<address>Apache/2.4.10 (Debian) Server at burningchrome.com Port 80</address>
	</body></html>
----------------------------------------------------------------------
Ran 1 test in 0.039s

FAILED (failures=1)
```

**Comment by keyhan** [comment]
Look at 124 I put the printout there

**Comment by keyhan** [comment]
This is printout when you expect 200 but get a 404

eyhan@keyhan-desktop:~/gabbi$ py.test --junitxml=/home/keyhan/gabbi/result.xml -svx test_keyhan.py 
================================================== test session starts ==================================================
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/keyhan/gabbi, inifile: 
collected 3 items 

test_keyhan.py::test_gabbits::['start_driver_google_scenario_do_get_to_google.se'] <- ../../../usr/local/lib/python2.7/dist-packages/gabbi/suite.py PASSED
test_keyhan.py::test_gabbits::['driver_google_scenario_do_get_to_google.se'] <- ../../../usr/lib/python2.7/unittest/case.py FAILED

----------------------------------- generated xml file: /home/keyhan/gabbi/result.xml -----------------------------------
======================================================= FAILURES ========================================================
______________________________ test_gabbits['driver_google_scenario_do_get_to_google.se'] _______________________________

self = <gabbi.driver.driver_google_scenario_do_get_to_google.se testMethod=test_request>
args = (<gabbi.reporter.PyTestResult run=1 errors=0 failures=0>,), kwds = {}

    def __call__(self, *args, **kwds):
>       return self.run(*args, **kwds)

/usr/lib/python2.7/unittest/case.py:393: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python2.7/dist-packages/gabbi/case.py:117: in run
    super(HTTPTestCase, self).run(result)
/usr/lib/python2.7/unittest/case.py:333: in run
    result.addFailure(self, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <gabbi.reporter.PyTestResult run=1 errors=0 failures=0>
test = <gabbi.driver.driver_google_scenario_do_get_to_google.se testMethod=test_request>
err = (<class '_pytest.assertion.reinterpret.AssertionError'>, AssertionError(u'\'404\' not found in [\'200\'], response:\n<....</code> was not found on this server.  <ins>That\u2019s all we know.</ins>\n',), <traceback object at 0x7f0c9bffa098>)

    def addFailure(self, test, err):
>       raise err[1]
E       AssertionError: '404' not found in ['200'], response:
E       <!DOCTYPE html>
E       <html lang=en>
E         <meta charset=utf-8>
E         <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
E         <title>Error 404 (Not Found)!!1</title>
E         <style>
E           *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
E         </style>
E         <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
E         <p><b>404.</b> <ins>That’s an error.</ins>
E         <p>The requested URL <code>/gosndkdksadl/dsdsdsd/dsdssd</code> was not found on this server.  <ins>That’s all we know.</ins>

/usr/local/lib/python2.7/dist-packages/gabbi/reporter.py:109: AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================== 1 failed, 1 passed in 0.21 seconds ===========================================

**Comment by keyhan** [comment]
I used now the latest 1.7.2 and when I look at generated junit xml file, then it is filled data as above, that should be fixed too.

**Comment by cdent** [comment]
There are three different things going on here, which need different solutions:

* pytest `-sv` is _loud_. If you run pytest without those arguments the volume of output is less. You might also want to use `--tb=short`
* When pytest creates tests using the `yield` method being used in gabbi, it's name for the test is pretty complex (as you've seen), but that's just the way pytest works and is not something gabbi can really control (until we switch away from the yield style)
* The output of the test failure (when using `--tb=short`) is effectively the same when using pytest as it is when using unittest to run the gabbi tests. It sounds like you don't like this level of verbosity, or somehow it is not serving what you need. Can you give me an example of what you think it should look like? From there perhaps we can figure something out. At the moment the output is intentionally quite noisy (for example if the status code is not what is expected, than part of the body of the response is provided, in case that helps determining the reason for the failure).

**Comment by keyhan** [comment]
Thanks, I used the flags like you said and it reduced the printouts. I have not used it with jenkins yet so I do not how the end result would look like there.

**Comment by cdent** [comment]
If your main issue is wanting the junitxml results, you can run gabbi with testr or subunit and then turn the subunit output into xml with subunit2junitxml.

For an example try this:

```shell
git clone git@github.com:cdent/gabbi.git
cd gabbi
tox -epy27
testr last --subunit |subunit2junitxml  > j.xml
```

_you'll need tox and testrepository install from pypi._

If there's a specific action you think needs to happen to improve gabbi, could you open a new ticket with that in it please?
