### ISSUE TITLE
pytest test count is inaccurate

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#128]
The stop and start methods of the TestSuite (which makes sure fixtures are started) are currently counted as tests, so for each yaml file there are N+2 tests.

Fixing this probably requires becoming properly acquainted with the pytest test collection and fixture handling and not using the current form of yielding tests.

**Comment by cdent** [comment]
See #124 for additional discussion.

**Comment by jasonamyers** [comment]
I see this in my nose plugin as well

**Comment by cdent** [comment]
Yeah, I'm not sure how to fix it.

Probably the right way to fix it is to use pytest/nose correctly instead of hacking around with manipulating TestSuite and TestCase into being almost but not quite okay for use with pytest and nose, but I haven't had a chance to investigate.
