### ISSUE TITLE
Recursion for gabbits across all subdirs of test_dir

### ISSUE THREAD

**Issue by josdotso** [cdent/gabbi#143]
I would like to structure my "live" gabbits directory in the following manner.

gabbits/team-x/api-x1/foo.yaml
gabbits/team-y/api-y1/bar.yaml

When calling the generator/load function for pytest, I found that the loader doesn't recurse if I specify  `test_dir=os.path.join(os.path.dirname(__file__), 'gabbits')`.

I think there are several ways I could solve this, some of which require changes to neither py_test_generator nor build_tests, but I thought I'd run this by you to see if you have any thoughts on the matter.

Here's my pytest runner as it sits today:
https://gist.github.com/josdotso/367907f3a775bed029afe0d19311a7a4#file-pytest-generator-py

**Comment by cdent** [comment]
Hmm, yeah. The original idea was that a non recursive directory was nicely explicit and clearly bounded. In that context the way to have more directories is to have more calls to `build_tests` or `py_test_generator`.

If we do want to do something where the loop in `build_tests` that loads the yaml recursed one thing we would have to decide is what that would mean in terms of test suites and test names and the semantics of what a subdirectory in a directory containing yaml means for the relationships between test suites (if anything). My initial thinking is that a directory would imply a suite, each yaml file a suite containing tests. So you could end up with a suite, containing a suite, containing a suite, contain tests...

Doing that would impact how fixtures work and would also have some impact on the concurrency grouping that can be used in `.testr.conf`.

The other option is that directories don't mean anything: The yaml is all found and loaded into the same suite. This would be easier to manage in the gabbi code but limits the value of the directories.

I'm going to cc in @FND and @jasonamyers to see if they have any ideas on the matter. Suffice to say that I think this is something worthy of discussion but it is unlikely we'll make a quick decision on how to do it. In the short term I'd say cook up a work around in your own test loader and add your own further comments to this thread and we'll see where it goes.

**Comment by josdotso** [comment]
Okay cool.  I can live with the way it is for now.  I can always separate into per-team gabbits dirs.  If you'd like to close this, it's cool with me.  Thanks!

**Comment by cdent** [comment]
Based on experience with large test suites since the time this bug was created, the issues mentioned above about concurrency and grouping are pretty important. Adding recursive directory handling will greatly complicate that, so I think we'll hold off.
