### ISSUE TITLE
Q: Can I regex in response_json_paths values (not keys)?

### ISSUE THREAD

**Issue by josdotso** [cdent/gabbi#146]
More for the FAQ perhaps...

I see in the example that regex is possible for headers, but how about for JSONPath (response_json_paths)?

http://gabbi.readthedocs.io/en/latest/example.html?highlight=regular%20expression

http://gabbi.readthedocs.io/en/latest/format.html#response-expectations

A good example is when we contact an endpoint expecting a server-side generated string to appear there (e.g. UUID).  In that case we might want to regex for n characters with some hyphens in predictable places.

Thanks!
P.S.  Re-implementing some existing tests in Gabbi is going VERY quickly compared to dev time with the older suites.  Rock on!

**Comment by cdent** [comment]
That wouldn't be too hard to do. Basically the same logic used in `HeadersResponseHandler` would be duplicated in the `JSONResponseHandler`.

Another option would be to get the content-handlers branch merged, and then you could write your own content-hander that subclasses (and thus replaces) the json handler and adds the functionality.

It seems a reasonable enough thing to add. Do you have the time interest to make a pull request? Don't feel obliged but if you do it would be a good but relatively straightforward contribution.

Glad to hear gabbi is working out for you. Once people actually try it they seem to dig it, but getting people to that point can sometimes be challenging.
