### ISSUE TITLE
Interpolate env vars that look like integers as Python integers.

### ISSUE THREAD

**Issue by josdotso** [cdent/gabbi#148]
Discussion was started here: https://github.com/cdent/gabbi/issues/144#issuecomment-224988014

**my initial ask:**

> p.s. rather than opening another issue immediately, another quick question: Is it possible to source integers from environment variables in the YAML? I ask because I just tried to source poll delay and count from environ, but test failed complaining about strings vs. integers. I tried unquoting the value during shell export, but no dice. Worth opening a new issue?

**@cdent's reponse from #144:**
> The issue with strings and ints is because environment variables are always strings, see this block of code. In that block it would be possible to turn things that look like ints into its.
> However, poll and count, don't use substitutions so even if the environment was producing stuff it wouldn't get pulled, so some fixes would be needed in the poll handling.
> Yeah, if you could make a fresh issue, that would be great.

@cdent Please let me know if you meant to create a fresh issue for the poll/count substitutions and not for this.  If so, I'll close this issue and open one on that.

**Comment by cdent** [comment]
I meant poll/count substitutions, sorry for being unclear, but let's leave this one here too, so we can track that as well. There's a similar problem (to this one) in #147. So there's a slew of "type" issues that need some thought at the overall level, not just the specific instance level. Having a few different issues going helps (at least it helps _me_) indicate the breadth of the high level issue.

**Comment by cdent** [comment]
I think we can close this one based on the explorations in #161 which suggest that how the interpolation happens is a bit context dependent. Please reopen or create another one if there are additional details which suggest otherwise.
