### ISSUE TITLE
gabbi doesn't think of jsohhome as `not_binary` and it probably should

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#158]
Because [json home documents](https://tools.ietf.org/html/draft-nottingham-json-home-02#section-3) have their own unique media type of `application/json-home` the `gabbi.utils.not_binary` method won't recognize a json-home doc as text. This should probably be fixed.

/cc @FND because I reckon he has more recent knowledge about jsonhome than @cdent

**Comment by FND** [comment]
I've struggled with this in the past, failing to come up with a pattern that's both generic and reliable - so ... ¯\_(ツ)_/¯

FWIW, when tackling this, we might also want to consider media types like `application/vnd.api+json; ext=jsonpatch`.

**Comment by cdent** [comment]
Anything `+json$` is supposed to already be covered, but it looks like there may be some issues with the different places that `not_binary` is called. Some of them do not also call the logic in `extract_content_type` (which splits on `;` and a few other things).

Apparently some more tests are in order when fixing this.

Actually just now when reading through the code I realized `application/json-home` does work, because the code is:

```
or content_type.startswith('application/json')
```

So, in fact the named bug is not one, but there are other issues. Will get back to this when I have a bit more attention.
