### ISSUE TITLE
Data <@filename isn't relative to the YAML file

### ISSUE THREAD

**Issue by tomviner** [cdent/gabbi#184]
The [docs say](https://gabbi.readthedocs.io/en/latest/format.html#data):

> If the value is a string that begins with <@ then the rest of the string is treated as the name of a file to be loaded from the same directory as the YAML file. 

But I haven't found it works like this unless I cd into the directory containing the yaml file.

`_load_data_file` says:
```python
path = os.path.join(self.test_directory, os.path.basename(filename))
```
this does a few things:
- makes the path begin with `self.test_directory` (defaults to `.`, the current working directory)
- disguards any folders in the <@ `filename` path
- appends `filename`

This means, if I'm in `/`, and I have a test that says `data: <@cake.jpg`, I cannot run my tests as advised in the docs:
`gabbi-run -- /my/test.yaml /my/other.yaml`

`FileNotFoundError: [Errno 2] No such file or directory: './cake.jpg'`

So in our test running script, we have to start with `cd tests/`.

My preference, would be to make the path relative to the location of the yaml file. That way, I can run my tests from whatever directory.

Obviously this isn't possible when redirecting with `<` as the filename is never seen by gabbi. So I'm happy is discuss other ideas.

---

Furthermore I can't keep my test data in a child directory, unless I cd into that directory like:
```shell
cd yaml_tests/test_data
gabbi-run -- ../test_things.yaml
```

So for that reason, I'd like to allow directories like `<@test_data/filename.txt` to be included in the path.

---

Happy to write the patch, if we come up with an approach here.

**Comment by cdent** [comment]
The `<@` stuff predates `gabbi-run` and was written the way you've correctly described to make sure that test suites that use the `driver.build_tests` method of finding and loading tests didn't inadvertently read data from places they shoudn't be. The most explicit way of doing that was by having only files adjacent to the yaml be readable.

As you noticed this goes a bit strange when using `gabbi-run`, especially now that there is the -f functionality.

I don't have any bright ideas on how to do this well, while still keeping build_tests constraints. I'm pinging @FND so he can comment too: he's one of the driving forces behind gabbi-run so may have some thoughts.

I'm sure we can figure something out.

**Comment by FND** [comment]
Given the constraints of backwards compatibility, I guess the only reasonable way forward here is for `runner` to set a working directory - either via an environment variable (`GABBI_CWD`? though I generally dislike those) or by passing an additional parameter through `suitemaker.test_suite_from_dict`.

**Comment by cdent** [comment]
@FND and I had a long conversation about this in IRC where were apparently completely agreeing with one another while completely misunderstanding one another. Typical.

Anyway, the conclusion from that is that there are two issues here:

* When passing in a file to `gabbi-run` the path to that file needs to become the `test_directory` that is provided to `test_suite_from_dict`. That's relatively easy to make happen and gets things at least working sensibly.
* More difficult is the test data in a child or adjacent directory. The `basename` call kills this. We could change that such that the path can be in `test_directory` or any descendants, but we wouldn't want to change it to allow anything outside of that tree as that would loosen the desirable constraint of not being able to get at data outside of the suite's context.

We can probably useful fix this in two steps: resolve the easy problem, see how that feels, and then decide how best to fix the harder problem.

Thoughts?

**Comment by tomviner** [comment]
Great, thanks for spending some thought cycles on this :-D

So your first point covers passing file(s) by *filename*, and would go a long way to making things easier for us. We'd need to add the caveat: *when redirecting test files via `gabbi-run < test.yaml`, `<@filename` will read files relative to the current directory.*

On your second point, can you help me understand the difficulty? I envisage something like:

```python
# filename can be relative or absolute
path = os.path.join(self.test_directory, filename)
# relpath takes care of normalising path for us
has_dir_traversal = os.path.relpath(path, start=self.test_directory).startswith(os.pardir)
```

This allows the user to enter any path they like, relative or absolute, but if the relative path starts with `..` then you can't play ball. What do you think?

**Comment by cdent** [comment]
> On your second point, can you help me understand the difficulty?

By "more difficult" I didn't mean to imply that it was difficult in the absolute, just a more invasive change in the guts of gabbi, rather than something at the outer layers. I probably should have used some other word.

Anyway: your suggestion looks good.

If you'd like to take this on, please go for it. The changes required in `gabbi/runner.py` will likely need a slight change to the interface of `run_suite` as it currently takes a filehandle, having disposed any reference to the filename earlier. If you want we can split the two changes.

**Comment by tomviner** [comment]
Ok, let's split the two changes. I'll work on allowing access to child directories of the `test_directory`.
