### ISSUE TITLE
Should be able to set verbose from command line

### ISSUE THREAD

**Issue by tomviner** [cdent/gabbi#185]
The `verbose` flag is most helpful when debugging. If I've got a run of tests in a yaml file, each dependant on the one before, when I get an error, I'd like to be able to turn on verbose mode to see what's happening from the first test onward. Ideally I could change one thing in one place, like adding `--verbose=headers` or similar.

Would you be open to considering this?

**Comment by cdent** [comment]
Yeah, that would be reasonable, and could be done in the same way that `force_ssl` is done in `gabbi/runner.py`.
