### ISSUE TITLE
Dynamic variable generation based in test data?

### ISSUE THREAD

**Issue by karhidle** [cdent/gabbi#219]
I have a specific scenario where the authentication token should be generated for every test and by using a few things like the request path and request method, which are defined in the yaml.
Given that, I’m unable to set the token by just using a fixture + os.environ.
Is there a way to achieve that?
Thanks!

**Comment by cdent** [comment]
Sorry for the delay in responding. I've been travelling. 

Could you produce a YAML sample of how things might look if gabbi already did what you need? I'm having trouble getting my head around the exactly details of what you're trying to do.

Are you aware of the full suite of [substitutions](https://gabbi.readthedocs.io/en/latest/format.html#substitution)? 

In the absence of anything else that might work for you, one thing you could do is make a very small WSGI application which returns the info you need (either in a header or json response) and then refer to it by $HEADERS or $RESPONSE. That's a bit heavyweight though.

If you can explain your scenario in a bit more detail, I might be able to come up with some ideas, or we can work out an effective new feature.

**Comment by cdent** [comment]
Closing due to lack of response. If there's additional input, please re-open.
