### ISSUE TITLE
query data from mysql compare response

### ISSUE THREAD

**Issue by EtheriousNatsu** [cdent/gabbi#226]
I need query data from mysql to compare response ,how should i do?

**Comment by cdent** [comment]
Thanks for your question, but we're going to need a lot more info to be able to help. Do you have some existing tests that you can share that are almost what you are trying to do, but don't work yet, so we can understand what you are doing?

It sounds like perhaps you need a [Fixture](https://gabbi.readthedocs.io/en/latest/fixtures.html) which sets up some data and then stores some of it in environment variables which you are then able to use later in tests for a [subsitution](https://gabbi.readthedocs.io/en/latest/format.html#substitution).

Some examples of doing this are in the tests for the placement service within openstack. Have a look at the [fixtures.py](https://github.com/openstack/nova/blob/master/nova/tests/functional/api/openstack/placement/fixtures.py) and the surrounding files for some ideas.

**Comment by cdent** [comment]
Closing due to no response. If you have additional input, please re-open.
