### ISSUE TITLE
Regression with 1.39.0 and empty reponse_headers field

### ISSUE THREAD

**Issue by jd** [cdent/gabbi#236]
One of the tests in Gnocchi has an empty `reponse_headers` field:
https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/tests/functional/gabbits/resource.yaml#L503

This broke the test suite in some way as one behaviour changed between Gabbi 1.38.0 and 1.39.0. I've bisected and the culprit is 8de923ac825bfeb34cd8c9384634c68ebda345bd.

This is not critical as the fix is easy on Gnocchi's side: remove the empty and useless `reponse_headers` field in the YAML file https://github.com/gnocchixyz/gnocchi/pull/599. Still, I thought it might be useful to report it just in case there's something bigger behind that we would have missed.

**Comment by cdent** [comment]
Thanks, sorry about that. Gabbi has CI against gnocchi but it's set up to allow it to fail and I failed to look at it recently.

Besides reporting the problem, it is good you pointed this out because the gnocchi test job is broken (no tests get run), so there's bigger fixing to fix.

**Comment by cdent** [comment]
Ugh, the py27-gabbi job is gone from gnocchi's tox.ini and the remaining ones appear to require prometheus, which seems to require snappy, which needs to build a c extension.

**Comment by jd** [comment]
And building a C extension is a problem?

**Comment by cdent** [comment]
It's slow. But other than that, not really.
