### ISSUE TITLE
Q: Getting error while using $History dictionary

### ISSUE THREAD

**Issue by ankajgoel** [cdent/gabbi#247]
Hi,

I am trying to use Gabbi, for my api tests. As part of tests, i am generating a token in test 1 and then passing that to subsequent tests(test2 and test3), as a header. 

In the screenshot attached has how i am writing my tests. so test1 and test2 works fine. however in third test(test3), when i am referencing test1, in header, I am getting below exception. It seems like it's still trying to refer test2. 

Could you please advice, if i am missing something in test3?   

Test structure in yaml file. 
![image](https://user-images.githubusercontent.com/9313208/39488404-c83d9d56-4d47-11e8-9b8c-9aed76eb7441.png)

Exception:

        AssertionError: unable to replace $RESPONSE in $HISTORY['Create_token'].$RESPONSE['$.access_token'], data unavailable: JSONPath '$.access_token' failed to match on data: '{'jobIdentifier': 'cadd2c2e-d04d-48a7-b0b2-24aee3358129', 'jobSubmittedOn': '2018-05-01T18:50:21'}'

**Comment by cdent** [comment]
Nice spot, you've found at least one bug. One problem seems to stem from your use of uppercase in your test names. This works elsewhere when using HISTORY, but with headers something is getting in the way. Can you try the same test file but use only lower case in your test names and in your HISTORY backreferences, and let me know if that fixes it.

In the meantime I'll try to trace down where things are going wrong.

Thanks.

**Comment by cdent** [comment]
Actually, that doesn't seem to be the problem, I was misreading my test case. Do try what I suggested but it ought not to be an issue.

Another question: can you tell me more about the environment you are testing in? Operating system, version of python etc. What version of gabbi? Are you using the latest version?

**Comment by cdent** [comment]
Another thing to try is putting `$HISTORY['Create_token'].$RESPONSE['$.access_token']` as a field in the `data` and see if the replacement problem is just in headers, or everywhere. That will help narrow things down.

**Comment by ankajgoel** [comment]
checked by putting HISTORY in data as well, same exception.  also tried by changing it to lowercase, still failing. 
Below are the config
OS: windows, running using cmd using yaml runner
Python: 3.5.2
Using latest gabbi....used pip to install it.

**Comment by cdent** [comment]
Thanks for the quick response. I'm not going to have a chance to look at this again today but will get to it ASAP. If it's a windows problem that wouldn't hugely surprise me: there's been insufficient testing with windows and you may have found a bug which only gets tickled by windows.

Can you provide more of the output you are seeing (the verbose request and response bodies), with the private parts obscured? I'm interested in seeing the full structure of the requests and responses.

Also can you confirm that `Gabi_test1` is passing and behaving as expected?

**Comment by ankajgoel** [comment]
Thanks for looking into this.  I just released that even though i had pip install gabbi, it was 1.28...i had to upgrade to 1.42.1 and now its working fine. 
I should have checked that first thing...Sorry about confusion. 
Thanks Again.

**Comment by cdent** [comment]
No problem, I'm glad you got it working in the end. I hope gabbi proves useful for you.
