### ISSUE TITLE
Variable is not replace to previous result in a request body

### ISSUE THREAD

**Issue by taget** [cdent/gabbi#262]
Seen from https://gabbi.readthedocs.io/en/latest/format.html#any-previous-test

There are 2 requests:

1. post a task,  will return a taskId
2. query the task with the taskId

     
* previous test return:
{"dataSet": {"header": {"serverIp": "xxx.xxx.xxx.xxx", "version": "1.0", "errorKeys": [{"error_key"
: "2-0-0"}], "errorInfo": "", "returnCode": 0}, "data": {"taskId": "3008929"}}}

* yaml define
  data:
            taskId: $HISTORY['start live migrate a vm'].$RESPONSE['$.dataSet.data.taskId']

* actual result:
        "data": {
          "taskId": "$.dataSet.data.taskId"
        }

**Comment by cdent** [comment]
Can you post the actual YAML of your tests, that will help me understand what might be going on.

**Comment by taget** [comment]
`live_migration.yaml
defaults:
    request_headers:
        Host: test.vstation.qcloud.com
        X-QCloud-User-ID: 280078820
        X-QCloud-Component-ID: qctestsite
        X-QCloud-Transaction-ID: 99b5e60e-674f-4d2b-de82-1f905bf0d1b8

tests:

- name: start live migrate a vm
  verbose: True
  POST: /api/cgi
  request_headers:
    content-type: application/json
  data:
    params:
      content:
        requestInfo:
          requestKey: mx_ksdionuj3djfk
          caller: vs-api
          requestModule: csig
          seqId: ''
          requestId: ''
          operator: csig
        version: '1.0'
        type: json
        requestItem:
          data:
            detail:
            - uuid: ea766aaa-2fc3-4db1-898e-6ae60ddd1fd6
              hostIpList:
              - 10.112.92.171
              migrateBandwidth: 20
              migrateTimeout: 3600
              pauseTime: 100
              schedulerDebug: 'off'
              rawRootSwitch: 'on'
          method: instance_live_migrate
  status: 200

- name: query live migrate status
  verbose: True
  POST: /api/cgi
  request_headers:
    content-type: application/json
  data:
    params:
      content:
        version: '1.0'
        type: Json
        requestInfo:
          caller: des
          operator: des
          requestId: '14531925816833'
          requestKey: con
          requestModule: qcloud
          seqId: '145319249316116'
        requestItem:
          data:
            taskId: $RESPONSE['$.dataSet.data.taskId']
          method: instance_migrate_query
  status: 200
  response_json_paths:
    $.dataSet.header.returnCode: 0
  poll:
    count: 1
    delay: 1`

**Comment by taget** [comment]
Sorry for directly paste in the comments, here's the yaml http://paste.openstack.org/show/733948/

**Comment by taget** [comment]
BTW, I tried to change from 
$HISTORY['start live migrate a vm'].$RESPONSE['$.dataSet.data.taskId']
to 
$RESPONSE['$.dataSet.data.taskId']

no helps

**Comment by cdent** [comment]
What I would suggest you do is add a test of the response json paths of the first request to make sure that the response has you expect:

```yaml
status: 200
response_json_paths:
  $.dataSet.data.taskId: random_string
```

That will help to make sure that the response has _something_.

**Comment by taget** [comment]
> What I would suggest you do is add a test of the response json paths of the first request to make sure that the response has you expect:
> 
> ```yaml
> status: 200
> response_json_paths:
>   $.dataSet.data.taskId: random_string
> ```
> 
> That will help to make sure that the response has _something_.

Okay, will do that, and I am sure that the previous request has expected response.

Wonder if we can use the magical variable could be used in a request body (data)?

**Comment by cdent** [comment]
I've just added this test into the code which demonstrates the feature you're talking about and it works:

```
+
+    - name: post data for next
+      POST: /
+      request_headers:
+          content-type: application/json
+      data:
+          pets:
+              type: cat
+
+    - name: post data from prior response
+      POST: /
+      request_headers:
+          content-type: application/json
+      data:
+          pets:
+              type: $RESPONSE['$.pets.type']
+      response_json_paths:
+          $.pets.type: cat
```

Is that like what you are trying to do?

**Comment by taget** [comment]
> + pets:

yes, exactly.

It seems, that the response is 
`< Content-Type: text/plain; charset=utf-8`
so gabbit can not grab correct content from the RESPONSE variable.

Is there ways to handle that?

**Comment by cdent** [comment]
You need to fix the API. If it is returning JSON, but marking it as content-type: text/plain, then the API has a very large bug that needs to be fixed.

If for some reason it really needs to be text/plain, you could explore making a [response handler](https://gabbi.readthedocs.io/en/latest/handlers.html).

**Comment by taget** [comment]
OK, thanks @cdent for your time and quick response, I will close this issue.
