### ISSUE TITLE
consistent capitalization

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#28]
it appears there's no canonical spelling of "gabbi" (or "Gabbi"?)

I realize that `gabbi` is the technical (package) name, but the documentation should refer to it as either gabbi or Gabbi, consistently

**Comment by cdent** [comment]
As far as I can tell the only place it is "Gabbi" is in titles and initial word in a sentence, which makes sense to me.

Patches accepted if you see otherwise, otherwise close?

**Comment by cdent** [comment]
Okay, I found one, in the readme

**Comment by FND** [comment]
> it is "Gabbi" [...] in titles and initial word in a sentence

IMO proper names should be spelled consistently regardless of context - i.e. either you always capitalize or you never do.
