### ISSUE TITLE
Gabbi isn't SNI-aware

### ISSUE THREAD

**Issue by scottwallacesh** [cdent/gabbi#305]
Gabbi isn't compatible with HTTPS servers that require SNI.

**Comment by scottwallacesh** [comment]
Can we re-open this issue until it's fully resolved/released?

**Comment by scottwallacesh** [comment]
Part of #310

**Comment by cdent** [comment]
Yeah, sure, I had thought that the delay with getting the urllib3 that has the fix released would resolve quickly, but for some reason it has not. Hunting up more details.

**Comment by scottwallacesh** [comment]
Closing as v2.6.0 now contains SNI-compatible functionality.

**Comment by cdent** [comment]
> Closing

Thanks for taking care of that. I had fallen into such a deep hole with the revealed pytest bug that I forgot to do some of the housekeeping.
