### ISSUE TITLE
Unable to make a relative Content Handler import from the command-line

### ISSUE THREAD

**Issue by scottwallacesh** [cdent/gabbi#311]
On the command line, importing a custom Content Handler using a relative path requires manipulation of the `PYTHONPATH` environment variable to add `.` to the list of paths.

Should Gabbi allow relative imports to work out-of-the-box?

e.g. 
```
gabbi-run -r foo.bar:ExampleContentHandler < example.yaml
```
... fails with, `ModuleNotFoundError: No module named 'foo'`.

Updating `PYTHONPATH`...
```
PYTHONPATH=${PYTHONPATH}:. gabbi-run -r foo.bar:ExampleContentHandler < example.yaml
```
... works.

**Comment by cdent** [comment]
/cc @FND 

I had thought we already had a work around for this. Will try to refresh my memory.

**Comment by scottwallacesh** [comment]
We could "detect" a relative import if it was declared as, `.foo.bar:...` and only update the PyPath for the handler initialisation.  Something like... 
```python
def initialize_handlers(response_handlers):
    # Save PyPath
    pypath = sys.path

    custom_response_handlers = []
    handler_objects = []
    for import_path in response_handlers or []:
        # Check if a relative import was provided
        if import_path.startswith('.') and '.' not in sys.path:
            # Allow relative imports
            sys.path.append('.')
        for handler in load_response_handlers(import_path):
            custom_response_handlers.append(handler)
    for handler in handlers.RESPONSE_HANDLERS + custom_response_handlers:
        handler_objects.append(handler())

    # Restore PyPath
    sys.path = pypath
    return handler_objects
```

**Comment by cdent** [comment]
> We could "detect" a relative import if it was declared as, `.foo.bar:...`

That could work but I worry it might be a bit too magical. I suppose it does look enough like a relative import to imply as much.

Any corner cases we're not thinking of?

It's clear enough to document: "If you want to load a module from the local dir prepend a dot..."

**Comment by scottwallacesh** [comment]
> Any corner cases we're not thinking of?

Not that I can think of right now.

**Comment by scottwallacesh** [comment]
Either implementation would work, IMHO. As you say, a `-l` argument would be less "magical".  We're already having to write `-r ...` anyway and it would be simple enough to make it, `-lr ...`.

**Comment by scottwallacesh** [comment]
Oh dear.  Many failed tests.  I'll have to understand how they're run and work out what's going on there.

**Comment by scottwallacesh** [comment]
I don't have some of the older Python versions available, so some tests failed locally.  Everything looks okay...?

```plain
___________________________________________________________________________ summary ____________________________________________________________________________
  pep8: commands succeeded
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
  py39: commands succeeded
ERROR:  pypy3: InterpreterNotFound: pypy3
  limit: commands succeeded
  failskip: commands succeeded
  docs: commands succeeded
  py39-prefix: commands succeeded
  py39-limit: commands succeeded
  py39-verbosity: commands succeeded
  py39-failskip: commands succeeded
ERROR:  py36-pytest: InterpreterNotFound: python3.6
ERROR:  py37-pytest: InterpreterNotFound: python3.7
  py38-pytest: commands succeeded
  py39-pytest: commands succeeded
```

**Comment by cdent** [comment]
Yeah, that looks reasonable. I assume this is after you fixed the [line too long](https://github.com/cdent/gabbi/runs/5629404649?check_suite_focus=true#step:5:14)?

**Comment by scottwallacesh** [comment]
It wasn't but the Github tests are green now.

**Comment by cdent** [comment]
I guess this means you've started using content or response handlers? Anything worth sharing?

**Comment by scottwallacesh** [comment]
Probably not.  We were going raise a different issue today with some proposals to allow "raw strings" for `response_headers` as we wanted to match exact URLs for `location:`.  e.g. `/foo/bar/` but as they're "wrapped" in `/`s they're treated as regex strings which doesn't work for us.  The current workaround, `/^\/foo\/bar\/$/`, was a bit ugly.

We had a proposal to disable the regex functionality but I wanted to check the issue hadn't been raised in the past and that's when I read up about custom Content Handlers.  I simply copied the existing `HeadersResponseHandler` and removed the regex code and updated the `test_key_suffix` value.  That's when I came across the `PYTHONPATH` issue.

**Comment by scottwallacesh** [comment]
Of course, if we write an interesting custom Content Handler, we'll share it!

**Comment by cdent** [comment]
Ah okay. If you had showed up and said "we want a raw strings for response headers thing" I probably would have responded with "make a response handler, and then you can make it do all sort of things you might like". So good to hear you found your own way there.
