### ISSUE TITLE
Array of JSON objects in response body causing ValueError in YAML $RESPONSE variable

### ISSUE THREAD

**Issue by kiminoa** [cdent/gabbi#36]
ValueError: JSONPath '$.id' failed to match on data: '[{u'can_change_state': True, u'id': u'14998924', u'errors': []]'

I've got a REST call that returns an array of objects which I can limit to a single item, but still returns in its array form, as the snippet above shows. The corresponding YAML entry causing this is $RESPONSE['$.id']

I also tried $RESPONSE[0]['$.id'] but I think the unicodification of the JSON is wreaking havoc.

Any clever thoughts for working with/around this?

**Comment by kiminoa** [comment]
Kind of eyeing this snippet, but I haven't dug in to be confident:

```python
    def _json_replacer(self, match):
        """Replace a regex match with the value of a JSON Path."""
        path = match.group(1)
        return str(self.extract_json_path_value(self.prior.json_data, path))
```

**Comment by kiminoa** [comment]
I spent some more time looking at this later in the day, and am more suspicious of the regex in:

```python
    def _response_replace(self, message):
        """Replace a JSON Path from the prior request with a value."""
        return re.sub(r"\$RESPONSE\['([^']+)'\]",
                      self._json_replacer, message)```

Looks like the regex isn't ready to take on potential indexing here.

**Comment by cdent** [comment]
If your data is as follows (I assume this is what you meant, what you pasted appears to slightly incomplete):

```python
[
    {
        u'can_change_state': True,
        u'id': u'14998924',
        u'errors': []
    }
]
```

Then the JSONPath for getting id is `$[0].id` and the way to represent that in a `$RESPONSE` is as `$RESPONSE['$[0].id']` _not_  `$RESPONSE[0]['$.id']`. The entire JSONPath statement needs to be inside the `['<json path goes here>'].

[Here's an example](https://github.com/openstack/ceilometer/blob/4286fc027126a27948b45dd5bd3e852455f8d9c1/ceilometer/tests/gabbi/gabbits/resources-fixtured.yaml#L12-L22).

Does that make sense? Does it do what you're actually trying to do? Is there a part of the documentation that could be made more clear on this topic?

If it does fix it, go ahead and close this, but if not please follow up with more info.

**Comment by kiminoa** [comment]
Brilliant!

1. I need to keep that ceilometer example open.
2. Based on my, like, 002 understanding of the universe, I'll make some doc suggestions to help other newbs.
3. I'm too ignorant to even ask this question right. I wasn't familiar with this kind of $.id / $[0].id annotation ... it looked vaguely perlesque to me, but that's all I had. What is it? What does everyone else know that lets them see that clearly that I don't have in my brain?

Thanks a million!

**Comment by cdent** [comment]
That $[0].id stuff is [JSONPath](http://goessner.net/articles/JsonPath/) which is linked from the first page of the docs, but not very visibly so I don't think it is just you: it's not clear. It would probably makes sense for somewhere in the docs to be links to that and to [jsonpath_rw](https://pypi.python.org/pypi/jsonpath-rw) (the implementation used by gabbi) that is much more discoverable and closely associated with the decriptions of the parts of the testing format that use jsonpath.

**Comment by kiminoa** [comment]
Bam. That was my miss. Thank you! As a newbie, I'd be looking for the breadcrumb in http://gabbi.readthedocs.org/en/latest/format.html and http://gabbi.readthedocs.org/en/latest/example.html where the replaceables are briefly discussed. To me JSONPath translated - poorly because I'm a bad translator! - to just a way of referring to the structure of JSON. Doh. Maybe just me, but I'll stick in a sprase breadcrumb for the $RESPONSE comment there for your approval. Thanks, Chris!

**Comment by cdent** [comment]
> I'll stick in a sprase breadcrumb for the $RESPONSE comment there for your approval

Awesome, thank you very much.
