### ISSUE TITLE
Using $ENVIRON to populate YAML booleans always evaluates True due to os.environ's string return

### ISSUE THREAD

**Issue by kiminoa** [cdent/gabbi#40]
I had a "clever" idea (since I sometimes don't know what I can't do until hindsight hits). Thoughts on whether this is worth amending? It'd sure be a nice feature :) Would also enable env-specified replacers for the ssl, xfail and redirects booleans.

Verbose as "False" is evaluating to True because os.environ returns a string. RATS!

```yaml
defaults:
    verbose: $ENVIRON['GABBI_VERBOSE']
```

```python
      def start_fixture(self):                                                                        
         try:                                                                                        
             g_verbose = os.environ.get('GABBI_VERBOSE')                                             
             print "GABBI_VERBOSE={0}".format(g_verbose)                                             
         except KeyError:                                                                            
             os.environ['GABBI_VERBOSE'] = True 
```

```
GABBI_VERBOSE=False

###########################
GET https://url.com:443/v2/configurations
content-type: application/json
accept: application/json
authorization: Basic Z2FiYmlfQTo4ODc5YmNmZGJkYjQyMTM2M2Y3OWE3MDFhYzMwYmFiN2JiZGJiNmMz
```

If I were to do a pull request to enable myself, I've pondered:

Option 1:
Modify `case.py`'s `_run_test`conditional from
```
if test['verbose']:
```
to 
```
if test['verbose'] and (isinstance(test['verbose'], bool) or test['verbose'].lower() == "true"):
```

Option 2:
Modify `case.py`'s `_environ_replacer` to check for bools (and maybe integers? I don't have a good use case for that.) and re-cast the types before returning `os.environ[environ_name]`.

Possibly both of these are horrifically naïve for reasons I haven't considered.

**Comment by cdent** [comment]
Hmm, this is a rather interesting discovery, nice catch.

I think fixing it in _environ_replacer is probably the best way to go as that will allow it to work for all of verbose, ssl, redirects and xfail (the current suite of boolean flags). I'll experiment with that and see if I can come up with a reasonable solution.

I'll probably hold off on casting numbers until we have a concrete issue with them.
