### ISSUE TITLE
$ENVIRON can't access environment variables created in a fixture

### ISSUE THREAD

**Issue by kiminoa** [cdent/gabbi#43]
Can:
`env GABBI_VERBOSE="False" python -m unittest test_loader`

Can't:
fixtures.py
```python
class GabbiVarFixture(fixtures.GabbiFixture):
    <-- snip -->

    def start_fixture(self):
        try:
            os.environ.get('GABBI_VERBOSE')
        except KeyError:
            os.environ['GABBI_VERBOSE'] = "False"
```
test_thing.yaml
```yaml
fixtures:
    - GabbiVarFixture

defaults:
    verbose: $ENVIRON['GABBI_VERBOSE']
<-- snip -->
```
I'm sure I'm doing something wrong, and I know environment context can be infuriatingly tricky in Unix from dealing with it in crontabs, but I finish my work day with this conundrum. I'll do some research over the weekend and see if I can figure my way out of this problem.

Also, interesting:
If I use an $ENVIRON['var'] in my YAML settings for the booleans, like $ENVIRON['GABBI_VERBOSE'] and it loses the value due to the above problem, it will always evaluate as True. (default: False, so I think it's the $ENVIRON replacer throwing in a wrench)

**Comment by kiminoa** [comment]
Error, in the unlikely event it's gabbi and not me. It's probably me.

```
======================================================================
ERROR: test_request (gabbi.driver.test_env_loader_env_details_get_valid_configuration_details)
gabbi.driver.test_env_loader_env_details_get_valid_configuration_details.test_request
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 78, in wrapper
    func(self)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 118, in test_request
    self._run_test()
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 297, in _run_test
    headers[name] = self.replace_template(headers[name])
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 132, in replace_template
    message = getattr(self, method)(message)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 157, in _environ_replace
    self._environ_replacer, message)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 171, in _environ_replacer
    return os.environ[environ_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'GABBI_REQUEST_CONTENT_TYPE'
```

**Comment by kiminoa** [comment]
Yep. Daily idiot award goes to me.

**Comment by cdent** [comment]
I know you've closed this, but I thought I'd leave some comments anyway, just some thoughts to share:

* Some testrunners, I'm not sure which ones, will filter the environment before data is allowed into the testing structure. In most cases this happens at a layer above where your investigating things, such as [in tox](http://tox.readthedocs.org/en/latest/config.html?highlight=passenv#confval-passenv=SPACE-SEPARATED-GLOBNAMES) but it might show up in places.
* You can do `os.environ.get('GABBI_VERBOSE', 'False')` to avoid the KeyError exception handling (which wouldn't work as you've written it anyway as with `get` the second argument defaults to `None`.

Are things working

* as you expect?
* as the docs say?

now.

**Comment by kiminoa** [comment]
Yep. It was the faulty KeyError assumption that bit me. Took me almost 4 hours to narrow it down and discover my folly. Thank goodness I'm stubborn ... it's my only hope in the face of my astonishing ineptitudes ;)
