### ISSUE TITLE
$RESPONSE and json_response_paths fail if content-type isn't JSON

### ISSUE THREAD

**Issue by kiminoa** [cdent/gabbi#45]
Probably a feature request ...

Right now, our API supports XML and JSON and we'd ideally love to just toggle between the two. 

Because of the way gabbi does the response_strings, and using $ENVIRON in the defaults: for content-type/accept, we can so almost pull this off.

Two places where the fancy idea fails:
1. Any use of $RESPONSE with an XML content-type response will result in:
```
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 78, in wrapper
    func(self)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 118, in test_request
    self._run_test()
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 291, in _run_test
    base_url = self.replace_template(test['url'])
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 132, in replace_template
    message = getattr(self, method)(message)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 253, in _response_replace
    self._json_replacer, message)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Library/Python/2.7/site-packages/gabbi/case.py", line 202, in _json_replacer
    return str(self.extract_json_path_value(self.prior.json_data, path))
AttributeError: 'test_env_loader_env_notes_add_environment_note' object has no attribute 'json_data'
```
2. `json_response_paths:` can't be used and ignored when XML or non-JSON is detected. It would be lovely if this was possible. It'd be nice to get some "bonus" JSON tests when JSON is detected, and ignored with a warning otherwise.

**Comment by cdent** [comment]
If I'm understanding what you're saying the idea is that it ought to be possible to have $RESPONSE['$.stuff'] and response_json_paths in a test but for them to only be engaged if the content type on the associated test is JSON.

On the one hand I can see the appeal of this, done properly it would let you have a single set of tests that operates properly under a variety of circumstances.

On the other hand I'm not super keen: It would result in tests that contain assertions that only apply in some circumstances, circumstances you (as a reader) can't know while reading the tests. This would kill one of the main design goals of Gabbi: readable and fairly unambiguous tests.

That said, I think there are probably ways for you to accomplish something similar to what you want:

> Given that tests are YAML and lots of things are YAML you could write some base tests and a processing tool which read the YAML as input and output yet more YAML, some of which is tests for XML and some of which is tests for JSON. If you combined this with a response_xml_path handler that you wrote you'd have some pretty powerful tests that also happened to be reasonable artifacts.

That leaves open how to deal with RESPONSE handling of XML, which is probably a useful and warranted feature. I'd certainly be willing to review (and most likely) accept patches that added support for that but XML is not something I use in day to day work so nothing something that is going to come up as an immediate itch for me.

Finally, in your situation what I would probably end up doing is just writing (by hand) all the tests required for the different content types. Yes, this can feel like a lot of duplication, but it results in a collection of tests which are clear artifacts that describe the system being tested. I'm not opposed to automation at all but I think that there is a lot of temptation to automate the wrong things. Reading and writing tests is really for humans.

**Comment by kiminoa** [comment]
I'll see about doing a patch for the `$RESPONSE` and a `self.prior.xml_data` concept. Thanks!

**Comment by FND** [comment]
I very much agree with @cdent: I would hate for gabbi to include any magic  that obscures what's actually going on.

However, if you often have a set of tests that only differ WRT the content type, one could imagine a simple preprocessor that generates gabbi-compatible YAML from a slightly more abstract YAML format (essentialy a trivial form of templating).

**Comment by cdent** [comment]
I'm going to close this because the fix (extending response types) is larger than the issue and I'd prefer issues be things we're actively trying to fix. Please reopen if you disagree.

Having extensible response handling is definitely something we should look into for  v2.

**Comment by cdent** [comment]
For reference there is some early discussion [about this stuff](https://github.com/cdent/gabbi/wiki/Ideas#contenthandlers).

Does that look like it has potential @kiminoa? Gabbi still being a part of your work?

**Comment by kiminoa** [comment]
I'm on another project atm but we'll likely circle back to Gabbi, and expanded content handler support would be another feather in its cap. If development gets under way, ping me, as I'll probably have some day-to-day pragmatism to contribute to the CRs. Thanks!
