### ISSUE TITLE
deep links in documentation

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#57]
Would it be possible to provide deep links in the documentation? I just wanted to link to the default request method and response status, but there are no suitable anchors at http://gabbi.readthedocs.org/en/latest/format.html

**Comment by cdent** [comment]
Yes, I've wanted to do that for quite some time but haven't had the horsepower to figure out the rst/sphinx magic to make it happen while still having a simple list. If you know, or are willing to find out, go for it.

**Comment by cdent** [comment]
Now that we have the table, I'm going to go ahead and turn the table names into headings. This will allow the names to show up in the TOC in the sidebar.
