### ISSUE TITLE
magical variables enforce single quotes

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#58]
One of my tests contained the following line:

```yaml
url: $RESPONSE["$._links.next"]
```

That refused to work - it took me quite a while to figure out that's because gabbi seems to only accept single quotes there, as this worked just fine.

```yaml
url: $RESPONSE['$._links.next']
```

I would argue that users' expectation is that single and double quotes are equivalent.

**Comment by cdent** [comment]
I did it that way to keep the regex simple _and_ to make it clear that what is inside the ' is literal. Perhaps that's not enough of a justification. I can be convinced to change it, but you'd need to argue past:

* the literal thing above
* whether it is worth introducing the ambiguity into the docs (you can use ' or ") or whether just one way is better

Neither of those are super high insurmountable peaks, just something to consider.

**Comment by FND** [comment]
> make it clear that what is inside the ' is literal

As in, not interpolated? I understand the notion, but it still seems like a stretch to expect anyone to infer that. (That distinction doesn't even exist in many languages, including Python.)

> whether it is worth introducing the ambiguity into the docs

Without a doubt: yes. The refusal to accept double-quoted strings strikes me as highly unconventional, thus inevitably leading to confusion for some/many.
