### ISSUE TITLE
gabbi-run fails silently when providing incorrect server target

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#62]
I just ran `gabbi-run localhost 4000`, wondering why I kept getting "connection refused" errors - turns out the correct invocation is "localhost:4000".

Clearly this was my mistake, but it would be nice if gabbi was more accommodating, e.g. by

* detecting and reporting this (common?) error
* accommodating both "localhost:4000" and "localhost 4000" parameters (there's no general consistency in similar tools AFAICT)
* reporting host and port to STDERR before, allowing the user to see their mistake

**Comment by cdent** [comment]
In your example above 4000 is being taken as the prefix. Arg parsing is:

```
gabbi-run [host[:port]] [prefix]
```

Isn't connection refused a sufficient error report? Or is it that the error message is not sufficient?

Feel free to explore some options here, I haven't got any good ideas.

**Comment by cdent** [comment]
Does this matter as much now that we have:

```
usage: gabbi-run [-h] [-x] [-r [RESPONSE_HANDLERS]] [target] [prefix]

Run gabbi tests from STDIN

positional arguments:
  target                A fully qualified URL (with optional path as prefix)
                        to the primary target or a host and port, : separated
  prefix                Path prefix where target app is mounted. Only used
                        when target is of the form host[:port]

optional arguments:
  -h, --help            show this help message and exit
  -x, --failfast        Exit on first failure
  -r [RESPONSE_HANDLERS], --response-handler [RESPONSE_HANDLERS]
                        Custom response handler. Should be an import path of
                        the form package.module or package.module:class.
```

and target as URL is the preferred input?

**Comment by FND** [comment]
I suppose we can close this now, particularly because we we can't reasonably address the silent failure upon erroneous invocation.
