### ISSUE TITLE
clarify usage scenarios in docs (programmatic API vs. CLI)

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#71]
the former is largely relevant for Python implementations, the latter makes gabbi suitable as a general-purpose tools

(note that this should not result in the programmatic API being de-emphasized, because @cdent hates POSIX)

**Comment by cdent** [comment]
You've had nearly three years to think about it, any new ideas?

**Comment by FND** [comment]
Sadly, nothing immediately actionable - so closing until there's something more concrete to discuss.
