### ISSUE TITLE
output colorization (gabbi-run)

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#73]
In order to make it easier/quicker to interpret results at a glance, it would be useful if `gabbi-run` *optionally* highlighted success vs. failure:

> Ran 4 tests in 0.012s
>
> FAILED (failures=3)

would appear in red while

> Ran 5 tests in 0.482s
>
> OK

would appear in green

**Comment by cdent** [comment]
If you really want it and you're willing to implement it that's fine with but some constraints:

* It should default to off (as you've already said)
* Even if it is turned on, if the output is not a tty then it should be turned off (getting ansi escape sequences in log files is zomg the worst thing ever). [isatty](http://stackoverflow.com/questions/858623/how-to-recognize-whether-a-script-is-running-on-a-tty) ought to do that job.

**Comment by cdent** [comment]
I, surprisingly, did some research into this. While it is easy to get colors in this part:

```
... E create an object with a uuid
... ✗ get that uuid object

ERROR: create an object with a uuid
	Unable to find the server at stub
FAIL: get that uuid object
	unable to replace $LOCATION in $LOCATION, data unavailable: 'input_create_an_object_with_a_uuid' object has no attribute 'location'
```

It is not in this part:

```
----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (failures=1, errors=1)
```

The former is driven by TextTestResult but the latter is part of TextTestRunner (in its very long `run` method). Changing run to use colors would mean duplicating that long method, which doesn't have a good shelf life.

What I currently have as a prototype is some code that will turn the ✔ green and the E and X red. Which is pretty but doesn't quite have the same impact.

![screen shot 2015-08-06 at 15 46 27](https://cloud.githubusercontent.com/assets/34498/9114540/56c01c16-3c52-11e5-81e1-f09f1e78a20d.png)

Worth it or no?

**Comment by FND** [comment]
Your diff (discussed on IRC) seemed reasonably clean, so I'd say go for it - we can always give make it better another time.

**Comment by cdent** [comment]
I merged in the start, cuz why not. Feel free to either keep this issue open or make a new one that describes the next steps.

**Comment by cdent** [comment]
I think we'll close this in favor of more focused issues with the current color implementation.
