### ISSUE TITLE
considere integrating python-jsonpathw-ext

### ISSUE THREAD

**Issue by cdent** [cdent/gabbi#86]
@sileht made https://pypi.python.org/pypi/jsonpath-rw-ext and it's rather useful

**Comment by cdent** [comment]
The upstream [pull request](https://github.com/kennknowles/python-jsonpath-rw/pull/30) is getting some attention so looks like this will likely get merged into jsonpath-rw itself, in which case we get this stuff (len, sorted, filter) for free and can remove our own custom len.

**Comment by cdent** [comment]
The pull request is stalled so we may want to use sileht's thing. Opinions?

**Comment by cdent** [comment]
@sileht Do you consider your pull request to be pretty much dead and the right way to go is to use your extensions?

**Comment by sileht** [comment]
Yes, I think the PR is dead too.
