### ISSUE TITLE
group keys in format documentation

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#91]
The [Test Format](https://github.com/cdent/gabbi/blob/master/docs/source/format.rst) documentation page currently lists all keys as a lengthy list in seemingly arbitrary order.

This might be more comprehensible (and less daunting) if keys were grouped: metadata (name, description), request parameters, response expectations, settings (verbose, polling) - there might be more.

Also, table layout might improve readability (or scannability) by providing some visual consistency.

**Comment by cdent** [comment]
Yeah, all those suggestions make good sense. It is as it is now just because nobody else has made it better yet.

**Comment by FND** [comment]
I made a start in 5be28eb94de68a668949563b1cd306fa2480a633. It does seem easier to consume, but ReST tables are a bit tedious to create (let alone maintain). Worth pursuing?

**Comment by cdent** [comment]
It is better than the other way so probably worth pursuing. Yes, it is tedious to create but given how rarely we should be adding things not too bad.

**Comment by FND** [comment]
All keys should now be documented in this new format: 9da8c62765e3086150db4bb5b6e584c1ba42c954

You might want to check my editorial changes.

I left the rest mostly untouched - I hope that doesn't create too many inconsistencies.
